 /**
 ============================================================================
 Name        : pets.c
 Author      : Gonzalo Sinnott Segura
 Version     :
 Copyright   :
 Description : Library pets.c
 ============================================================================
 */

#include <stdio_ext.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include "utn.h"
#include "veterinaria.h"
#include "owners.h"
#include "pets.h"

static int pet_generateNewId(void);

int pet_addHardcode(Pets* pet_list, int pet_len, int *pet_firstLoad)
{
	int retorno = -1;
	if(pet_list != NULL && pet_len >0)
	{
		int pet_id[]={1,2,3,4,5,6,7,8,9,10};
		char pet_name[][20]={"Michi","Firulais","Dobby","Bobby","Chatran","Pucky","Michifus","Bolt","Dexter","Ayudante de santa"};
		int pet_age[]={3,2,4,1,2,3,1,5,6,2};
		char pet_breed[][20]={"Gato","Perro","Perro","Perro","Gato","Gato","Gato","Perro","Gato","Perro"};
		int pet_IdOwner[]={1,2,1,1,2,3,5,5,1,2};

		for(int i = 0; i < 10; i++)
		{
			pet_addData(pet_list, pet_len, pet_id[i], pet_name[i], pet_breed[i], pet_age[i], pet_IdOwner[i]);
		}
		*pet_firstLoad = TRUE;
	}
	return retorno;
}


/**
 * \brief initPets: To indicate that all positions in the array are empty,
 * this function put the flag (isEmpty) in TRUE in all position of the array
 * \param sEmployee* pet_list: Pointer to array of employees
 * \param int pet_len: Array pet_length
 * \return (-1) Error / (0) Ok
 */

int initPets(Pets* pet_list, int pet_len)
{
	int retorno = -1;
	if(pet_list != NULL && pet_len > 0)
	{
		for(int i=0;i<pet_len;i++)
		{
			pet_list[i].pet_isEmpty= TRUE;
		}
		retorno = 0;
	}
	return retorno;
}

/**
 *  \brief pet_alta: Asks the user for the pet data
 * \param Pets* pet_list: Pointer to array of pets
 * \param int pet_len: Array pet_length
 * \param int pet_firstLoad: Pointer to space in memory where is the
 *  variable to indicate if an entry is loaded
 * \return (-1) Error / (0) Ok
 */

int pet_alta(Pets* pet_list,int pet_len, int *pet_firstLoad)
{
	int retorno = -1;
	int pet_id;
	char pet_name[LONG_NOMBRE];
	char pet_breed[LONG_NOMBRE];
	int pet_age;
	int pet_IdOwner;
	int index;

	if(pet_list != NULL && pet_len > 0 && pet_firstLoad >0 && pet_checkFirstEmptyIndex(pet_list, pet_len, &index)==0)
	{
		if(pet_getForm(pet_name, pet_breed, &pet_age, &pet_IdOwner)== 0)
		{
			pet_id=pet_generateNewId();
			if(pet_addData(pet_list, pet_len, pet_id, pet_name, pet_breed, pet_age, pet_IdOwner)==0)
			{
				*pet_firstLoad = TRUE;
				retorno=0;
			}
		}
		else
		{
			printf("\nERROR EN LA CARGA DEL EMPLEADO.\n");
		}
	}
	else
	{
		printf("\nNO SE PUEDEN CARGAR MAS REGISTROS.\n");
	}
	return retorno;
}

/**
 *  \brief checkFirstEmptyIndex: Checks first empty index in the array
 * this function search the array for the first index with the value TRUE in the isEmpty item
 * \param sEmployee* pet_list: Pointer to array of employees
 * \param int pet_len: Array pet_length
 * \param int *EmptyIndex: Pointer to position of first empty index.
 * \return (-1) Error / (0) Ok
 */

int pet_checkFirstEmptyIndex(Pets* pet_list, int pet_len, int *emptyIndex)
{
	int retorno = -1;
	if(pet_list != NULL && pet_len >0 && emptyIndex != NULL)
	{
		for(int i = 0; i < pet_len; i++)
		{
			if(pet_list[i].pet_isEmpty == TRUE)
			{
				*emptyIndex = i;
				retorno = 0;
				break;
			}
		}
	}
	return retorno;
}

/**
 *  \brief pet_getForm: Brings up a menu for the user to complete with info
 * \param char *pet_name: Pointer to place to store pet_name
 * \param char *lastName: Pointer to place to store last pet_name
 * \param float *salary: Pointer to place to store salary
 * \param int *sector: Pointer to place to store sector
 * \return (-1) Error / (0) Ok
 */

int pet_getForm(char *pet_name, char *pet_breed, int *pet_age,int *pet_IdOwner)
{
	int retorno = -1;

	if(pet_name != NULL && pet_breed != NULL && pet_age > 0 && pet_IdOwner > 0)
	{
		if((utn_getString("Ingrese Nombre de la Mascota:", "Error. ", pet_name, 3, LONG_NOMBRE)==0) &&
		   (utn_getAlphaNum("Ingrese Raza:", "Error. ", pet_breed, 3, LONG_NOMBRE)==0) &&
		   (utn_getIntNumber("Ingrese Edad:", "\nError. ", pet_age, 3, 2,1)== 0) &&
		   (utn_getIntNumber("Ingrese ID del dueño ", "\nError. ", pet_IdOwner, 3, INT_MAX, 0)== 0))
		{
			retorno = 0;
		}
	}
	return retorno;
}

/**
 *  \brief generateNewId: Generates a new ID that's +1 from previous loaded employee ID.
 */

static int pet_generateNewId(void)
{
	static int id = 10;

	id = id+1;
	return id;
}

/**
 *  \brief pet_addData: add in a existing pet_list of employees the values received
 *  as parameters in the first empty position.
 * \param Employee* pet_list: Pointer to array of employees
 * \param int pet_len: Array pet_length
 * \param int id: id generated by generateNewId() function
 * \param char pet_name[]: Input by user from getEmployeeForm
 * \param char lastName[]: Input by user from getEmployeeForm
 * \param float salary: Input by user from getEmployeeForm
 * \param int sector: Input by user from getEmployeeForm
 * \return (-1) Error / (0) Ok
 */

int pet_addData(Pets* pet_list,int pet_len, int pet_id, char pet_name[], char pet_breed[], int pet_age, int pet_IdOwner)
{
	int retorno = -1;
	int emptyIndex;

	if(pet_checkFirstEmptyIndex(pet_list, pet_len, &emptyIndex)==0)
	{
		pet_list[emptyIndex].pet_id=pet_id;
		strcpy(pet_list[emptyIndex].pet_name,pet_name);
		strcpy(pet_list[emptyIndex].pet_breed,pet_breed);
		pet_list[emptyIndex].pet_age = pet_age;
		pet_list[emptyIndex].pet_IdOwner = pet_IdOwner;
		pet_list[emptyIndex].pet_isEmpty=FALSE;
		retorno=0;
	}

    return retorno;
}

/**
 *  \brief pet_findById: find an Employee by Id then returns the index position in array.
 * \param Employee* pet_list: Pointer to array of employees
 * \param int pet_len: Array pet_length
 * \param int id: id to search
 * \return Return employee index position or (-1) if ERROR
 */

int pet_findById(Pets* pet_list, int pet_len,int id)
{
	int retorno;

	if (pet_list != NULL && pet_len > 0 && id > 0)
	{
		for (int i = 0; i < pet_len; i++)
		{
			if(pet_list[i].pet_isEmpty == FALSE && pet_list[i].pet_id == id )
			{
				retorno = i;
				break;
			}
		}
	}
	return retorno;;
}

/**
 * \brief pet_modifyMenu: Modifies the data of an Employee by given Id.
 * Allows to modify individual fields of the employee by a switch
 * \param Employee* pet_list: Pointer to array of employees
 * \param int pet_len: Array pet_length
 * \param int pet_firstLoad: variable to check if there is even one entry loaded
 * \return (-1) Error / (0) Ok
 */

int pet_modifyMenu(Pets* pet_list, int pet_len, int pet_firstLoad)
{
	int retorno = -1;
	int idToSearch;

	if(pet_firstLoad == FALSE)
	{
		printf("\nERROR. NO HAY DATOS INGRESADOS.\n");
	}
	else
	{
		if(utn_getIntNumber("Ingrese el ID a modificar:","Error, no es un ID valido. ",&idToSearch,3,INT_MAX,1)==0 &&
		   pet_modify(pet_list,pet_len,idToSearch)== 0)
		{
			retorno = 0;
		}
		else
		{
			printf("\nERROR, ID INEXISTENTE.\n");
		}
	}
	return retorno;
}

/**
 * \brief pet_modify: Modifies the data of an Employee by given Id.
 * Allows to modify individual fields of the employee by a switch
 * \param Employee* pet_list: Pointer to array of employees
 * \param int pet_len: Array pet_length
 * \param int pet_firstLoad: variable to check if there is even one entry loaded
 * \return (-1) Error / (0) Ok
 */

int pet_modify(Pets* pet_list, int pet_len,int id)
{
	int retorno = -1;
	int choosenOption;
	char answer;
	int indexToModify;

	Pets bufferPets;

	indexToModify = pet_findById(pet_list, pet_len, id);

	if(pet_list != NULL && pet_len>0 && id > 0 && indexToModify > -1)
	{
		do
		{
			printf("Pets a modificar\n");
			printf("Nombre y Direccion: %s %s Tipo: %d Precio por dia %.2f.\n",
					pet_list[indexToModify].pet_name,pet_list[indexToModify].pet_breed,pet_list[indexToModify].pet_age,pet_list[indexToModify].pet_IdOwner);
			if(utn_getIntNumber("\nQue campo desea modificar:"
								"\n 1-Nombre."
								"\n 2-Direccion."
								"\n 3-Tipo:"
								"\n 4-Precio por Dia:"
								"\nOpcion:", "\nError.", &choosenOption, 3, 4, 1)==0)
		{
			switch(choosenOption)
			{
				case 1:
					if(utn_getString("\nNombre:","\nError. ",bufferPets.pet_name,2,LONG_NOMBRE)==0)
					{
						strcpy(pet_list[indexToModify].pet_name,bufferPets.pet_name);
					}
					break;
				case 2:
					if(utn_getAlphaNum("\nDireccion:","\nError. ",bufferPets.pet_breed,2,LONG_NOMBRE)==0)
					{
						strcpy(pet_list[indexToModify].pet_breed,bufferPets.pet_breed);
					}
					break;
				case 3:
					if(utn_getIntNumber("Tipo (1-LED o 2-LCD):", "\nError. ", &bufferPets.pet_age, 3, 2, 1)==0)
					{
						pet_list[indexToModify].pet_age=bufferPets.pet_age;
					}
					break;
				case 4:
					if(utn_getFloatNumber("Precio por dia: ", "\nError. ", &bufferPets.pet_IdOwner, 3, INT_MAX, 0)==0)
					{
						pet_list[indexToModify].pet_IdOwner=bufferPets.pet_IdOwner;
					}
					break;
			}
		}
		utn_getChar("¿Desea seguir modificando este ID?(Y/N)", "Error. ", &answer, 'Y', 'N', 3);
		}while(answer!='N');
		retorno = 0;
	}
	return retorno;
}

/**
 * \brief pet_removeMenu: Remove a Employee by Id (put isEmpty Flag in TRUE)
 * \param Employee* pet_list: Pointer to array of employees
 * \param int pet_len: Array pet_length
 * \param int *pet_firstLoad: variable to check if there is even one entry loaded and
 *  safeguard to prevent errors if all data is erased
 * \return (-1) Error / (0) Ok
 */

int pet_removeMenu(Pets* pet_list, int pet_len,int *pet_firstLoad)
{
	int retorno = -1;
	int idToSearch;

	if(*pet_firstLoad == FALSE)
	{
		printf("\nERROR. NO HAY DATOS INGRESADOS.\n");
	}
	else
	{
		if(utn_getIntNumber("Ingrese el ID a eliminar:","Error, no es un ID valido. ",&idToSearch,3,INT_MAX,1)==0 &&
		   pet_remove(pet_list,pet_len,idToSearch)== 0)
		{
			for(int i = 0; i < pet_len; i++)
			{
				if(pet_list[i].pet_isEmpty == TRUE)
				{
					*pet_firstLoad = FALSE;
				}
				else
				{
					*pet_firstLoad = TRUE;
					break;
				}
			}
			retorno = 0;
		}
	}
	return retorno;
}

/**
 * \brief pet_remove: Remove a Employee by Id (put isEmpty Flag in TRUE)
 * \param Employee* pet_list: Pointer to array of employees
 * \param int pet_len: Array pet_length
 * \param int id: id value of entry to remove
 *  safeguard to prevent errors if all data is erased
 * \return (-1) Error / (0) Ok
 */

int pet_remove(Pets* pet_list, int pet_len,int id)
{
	int retorno = -1;
	int indexToModify;
	char answer;

	indexToModify = pet_findById(pet_list, pet_len, id);

	if(pet_list != NULL && pet_len>0 && id > 0 && indexToModify > -1)
	{
		printf("Pets a eliminar\n");
		printf("Nombre y Direccion: %s %s \n", pet_list[indexToModify].pet_name,pet_list[indexToModify].pet_breed);
		utn_getChar("¿Desea eliminar este ID?(Y/N)", "Error. ", &answer, 'Y', 'N', 3);
		switch(answer)
		{
			case 'Y':
				pet_list[indexToModify].pet_isEmpty = TRUE;
				printf("REGISTRO DE EMPLEADO BORRADO CON EXITO.");
				break;
			case'N':
				printf("REGISTRO NO BORRADO");
				break;
			default:
				printf("ERROR, INGRESE 'Y' PARA BORRAR EL REGISTRO.");
		}
		retorno = 0;
	}
	else
	{
		printf("\nERROR, ID INEXISTENTE.\n");
	}
	return retorno;
}

/**
 *  \brief pet_getReport: Reports employees by alphabetical order and numerical order
 *  of sector. Also gives info about total money spend on salaries, average salary and
 *  how many employees have a salary above the average.
 * \param Employee* pet_list: Pointer to array of employees
 * \param int pet_len: Array pet_length
 * \param int pet_firstLoad: variable to check if there is even one entry loaded
 * \return (-1) Error / (0) Ok
 */

int pet_getReport(Pets* pet_list, int pet_len, int pet_firstLoad)
{
	int retorno = -1;
	int sortOrder;

	if(pet_firstLoad == FALSE)
	{

		printf("\nERROR. NO HAY DATOS INGRESADOS.\n");

	}
	else
	{
		if(utn_getIntNumber("\n1- Orden Descendente"
						    "\n2- Orden Ascendente"
						    "\nOpcion:","Error. ",&sortOrder,3,2,1)==0)
		{
			if(pet_list!= NULL && pet_len > 0)
			{
				pet_sort(pet_list, pet_len, sortOrder);
				pet_print(pet_list, pet_len);
				retorno = 0;
			}
		}
	}
	return retorno;
}

/**
 *  \brief pet_sort: Sort the elements in the array of employees, the argument order
 * indicate UP or DOWN order
 * \param Employee* pet_list: Pointer to array of employees
 * \param int pet_len: Array pet_length
 * \param int order: [2] indicate UP (order Z->A) - [1] indicate DOWN (order A->Z)
 * \return (-1) Error / (0) Ok
 */

int pet_sort(Pets* pet_list, int pet_len, int order)
{
	int retorno = -1;
	int sorted;
	Pets bufferPets;

	if(pet_list != NULL && pet_len > 0 && (order == 1 || order == 2))
	do
	{
		sorted = TRUE;
		for(int i = 0; i < (pet_len-1); i++)
		{
			if((order == 1 &&
			  (strncmp(pet_list[i].pet_name, pet_list[i + 1].pet_name,LONG_NOMBRE)>0 ||
			  (strncmp(pet_list[i].pet_name, pet_list[i + 1].pet_name,LONG_NOMBRE)==0 &&
			   strncmp(pet_list[i].pet_breed, pet_list[i + 1].pet_breed,LONG_NOMBRE)>0))) ||
			   (order == 2 &&
			  (strncmp(pet_list[i].pet_name, pet_list[i + 1].pet_name,LONG_NOMBRE)<0 ||
			  (strncmp(pet_list[i].pet_name, pet_list[i + 1].pet_name,LONG_NOMBRE)==0 &&
			   strncmp(pet_list[i].pet_breed, pet_list[i + 1].pet_breed,LONG_NOMBRE)<0))))
			{
				bufferPets = pet_list[i];
				pet_list[i] = pet_list[i + 1];
				pet_list[i + 1] = bufferPets;
				sorted = FALSE;
			}
		}
	}while(sorted == FALSE);
	retorno = 0;
	return retorno;
}

/**
 * \brief pet_print: print the content of employees array
 * \param Employee* pet_list: Pointer to array of employees
 * \param int pet_len: Array pet_length
 * \return (-1) Error / (0) Ok*
 */

int pet_print(Pets* pet_list, int pet_len)
{
	int retorno = -1;
	if(pet_list != NULL && pet_len > 0)
	{
		printf("Nombre               |Raza        |Edad\n");
		for(int i=0;i< pet_len ;i++)
		{
			if(pet_list[i].pet_isEmpty == FALSE)
			{
				printf("%-20s %-15s %-6d\n",pet_list[i].pet_name,pet_list[i].pet_breed,pet_list[i].pet_age);
			}
		}
		retorno = 0;
	}
	return retorno;
}
