 /**
 ============================================================================
 Name        : pantalla.c
 Author      : Gonzalo Sinnott Segura
 Version     :
 Copyright   :
 Description : Library pantalla.c
 ============================================================================
 */

#include <stdio_ext.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include "mi_biblioteca.h"
#include "pantalla.h"
#include "publicidad.h"

static int generateNewId(void);

/**
 * \brief initPantalla: To indicate that all positions in the array are empty,
 * this function put the flag (isEmpty) in TRUE in all position of the array
 * \param sEmployee* list: Pointer to array of employees
 * \param int len: Array length
 * \return (-1) Error / (0) Ok
 */

int initPantalla(Pantalla* list, int len)
{
	int retorno = -1;
	if(list != NULL && len > 0)
	{
		for(int i=0;i<len;i++)
		{
			list[i].isEmpty = TRUE;
		}
		retorno = 0;
	}
	return retorno;
}

/**
 *  \brief pantalla_alta: Asks the user for the student data
 * \param Pantalla* list: Pointer to array of employees
 * \param int len: Array length
 * \param int firstLoad: Pointer to space in memory where is the
 *  variable to indicate if an entry is loaded
 * \return (-1) Error / (0) Ok
 */

int pantalla_alta(Pantalla* list,int len, int *firstLoad)
{
	int retorno = -1;
	int id;
	char name[LONG_NOMBRE];
	char address[LONG_NOMBRE];
	int pantallaType;
	float pricePerDay;
	int index;

	if(list != NULL && len > 0 && firstLoad >0 && checkFirstEmptyIndex(list, QTY_PANTALLAS, &index)==0)
	{
		if(pantalla_getForm(name, address, &pantallaType, &pricePerDay)== 0)
		{
			id=generateNewId();
			if(pantalla_addData(list, len, id, name, address, pantallaType, pricePerDay)==0)
			{
				*firstLoad = TRUE;
				retorno=0;
			}
		}
		else
		{
			printf("\nERROR EN LA CARGA DEL EMPLEADO.\n");
		}
	}
	else
	{
		printf("\nNO SE PUEDEN CARGAR MAS REGISTROS.\n");
	}
	return retorno;
}

/**
 *  \brief checkFirstEmptyIndex: Checks first empty index in the array
 * this function search the array for the first index with the value TRUE in the isEmpty item
 * \param sEmployee* list: Pointer to array of employees
 * \param int len: Array length
 * \param int *EmptyIndex: Pointer to position of first empty index.
 * \return (-1) Error / (0) Ok
 */

int checkFirstEmptyIndex(Pantalla* list, int len, int *emptyIndex)
{
	int retorno = -1;
	if(list != NULL && len >0 && emptyIndex != NULL)
	{
		for(int i = 0; i < len; i++)
		{
			if(list[i].isEmpty == TRUE)
			{
				*emptyIndex = i;
				retorno = 0;
				break;
			}
		}
	}
	return retorno;
}

/**
 *  \brief pantalla_getForm: Brings up a menu for the user to complete with info
 * \param char *name: Pointer to place to store name
 * \param char *lastName: Pointer to place to store last name
 * \param float *salary: Pointer to place to store salary
 * \param int *sector: Pointer to place to store sector
 * \return (-1) Error / (0) Ok
 */

int pantalla_getForm(char *name, char *address, int *pantallaType,float *pricePerDay)
{
	int retorno = -1;

	if(name != NULL && address != NULL && pantallaType > 0 && pricePerDay > 0)
	{
		if((utn_getString("Ingrese Apellido:", "Error. ", name, 3, LONG_NOMBRE)==0) &&
		   (utn_getAlphaNum("Ingrese Direccion:", "Error. ", address, 3, LONG_NOMBRE)==0) &&
		   (utn_getIntNumber("Ingrese Tipo (1-LED o 2-LCD):", "\nError. ", pantallaType, 3, 2,1)== 0) &&
		   (utn_getFloatNumber("Ingrese Precio: ", "\nError. ", pricePerDay, 3, INT_MAX, 0)== 0))
		{
			retorno = 0;
		}
	}
	return retorno;
}

/**
 *  \brief generateNewId: Generates a new ID that's +1 from previous loaded employee ID.
 */

static int generateNewId(void)
{
	static int id;

	id = id+1;
	return id;
}

/**
 *  \brief pantalla_addData: add in a existing list of employees the values received
 *  as parameters in the first empty position.
 * \param Employee* list: Pointer to array of employees
 * \param int len: Array length
 * \param int id: id generated by generateNewId() function
 * \param char name[]: Input by user from getEmployeeForm
 * \param char lastName[]: Input by user from getEmployeeForm
 * \param float salary: Input by user from getEmployeeForm
 * \param int sector: Input by user from getEmployeeForm
 * \return (-1) Error / (0) Ok
 */

int pantalla_addData(Pantalla* list,int len,int id,char name[], char address[], int pantallaType,float pricePerDay)
{
	int retorno = -1;
	int emptyIndex;

	if(checkFirstEmptyIndex(list, QTY_PANTALLAS, &emptyIndex)==0)
	{
		list[emptyIndex].id=id;
		strcpy(list[emptyIndex].name,name);
		strcpy(list[emptyIndex].address,address);
		list[emptyIndex].pantallaType = pantallaType;
		list[emptyIndex].pricePerDay = pricePerDay;
		list[emptyIndex].isEmpty=FALSE;
		printf("\nEl ID para la pantalla %s es: %d\n",list[emptyIndex].name,list[emptyIndex].id);
		retorno=0;
	}

    return retorno;
}

/**
 *  \brief pantalla_findById: find an Employee by Id then returns the index position in array.
 * \param Employee* list: Pointer to array of employees
 * \param int len: Array length
 * \param int id: id to search
 * \return Return employee index position or (-1) if ERROR
 */

int pantalla_findById(Pantalla* list, int len,int id)
{
	int retorno;

	if (list != NULL && len > 0 && id > 0)
	{
		for (int i = 0; i < len; i++)
		{
			if(list[i].isEmpty == FALSE && list[i].id == id )
			{
				retorno = i;
				break;
			}
		}
	}
	return retorno;;
}

/**
 * \brief pantalla_modifyMenu: Modifies the data of an Employee by given Id.
 * Allows to modify individual fields of the employee by a switch
 * \param Employee* list: Pointer to array of employees
 * \param int len: Array length
 * \param int firstLoad: variable to check if there is even one entry loaded
 * \return (-1) Error / (0) Ok
 */

int pantalla_modifyMenu(Pantalla* list, int len, int firstLoad)
{
	int retorno = -1;
	int idToSearch;

	if(firstLoad == FALSE)
	{
		printf("\nERROR. NO HAY DATOS INGRESADOS.\n");
	}
	else
	{
		if(utn_getIntNumber("Ingrese el ID a modificar:","Error, no es un ID valido. ",&idToSearch,3,INT_MAX,1)==0 &&
		   pantalla_modify(list,QTY_PANTALLAS,idToSearch)== 0)
		{
			retorno = 0;
		}
		else
		{
			printf("\nERROR, ID INEXISTENTE.\n");
		}
	}
	return retorno;
}

/**
 * \brief pantalla_modify: Modifies the data of an Employee by given Id.
 * Allows to modify individual fields of the employee by a switch
 * \param Employee* list: Pointer to array of employees
 * \param int len: Array length
 * \param int firstLoad: variable to check if there is even one entry loaded
 * \return (-1) Error / (0) Ok
 */

int pantalla_modify(Pantalla* list, int len,int id)
{
	int retorno = -1;
	int choosenOption;
	char answer;
	int indexToModify;

	Pantalla bufferPantalla;

	indexToModify = pantalla_findById(list, QTY_PANTALLAS, id);

	if(list != NULL && len>0 && id > 0 && indexToModify > -1)
	{
		do
		{
			printf("Pantalla a modificar\n");
			printf("Nombre y Direccion: %s %s Tipo: %d Precio por dia %.2f.\n",
					list[indexToModify].name,list[indexToModify].address,list[indexToModify].pantallaType,list[indexToModify].pricePerDay);
			if(utn_getIntNumber("\nQue campo desea modificar:"
								"\n 1-Nombre."
								"\n 2-Direccion."
								"\n 3-Tipo:"
								"\n 4-Precio por Dia:"
								"\nOpcion:", "\nError.", &choosenOption, 3, 4, 1)==0)
		{
			switch(choosenOption)
			{
				case 1:
					if(utn_getString("\nNombre:","\nError. ",bufferPantalla.name,2,LONG_NOMBRE)==0)
					{
						strcpy(list[indexToModify].name,bufferPantalla.name);
					}
					break;
				case 2:
					if(utn_getAlphaNum("\nDireccion:","\nError. ",bufferPantalla.address,2,LONG_NOMBRE)==0)
					{
						strcpy(list[indexToModify].address,bufferPantalla.address);
					}
					break;
				case 3:
					if(utn_getIntNumber("Tipo (1-LED o 2-LCD):", "\nError. ", &bufferPantalla.pantallaType, 3, 2, 1)==0)
					{
						list[indexToModify].pantallaType=bufferPantalla.pantallaType;
					}
					break;
				case 4:
					if(utn_getFloatNumber("Precio por dia: ", "\nError. ", &bufferPantalla.pricePerDay, 3, INT_MAX, 0)==0)
					{
						list[indexToModify].pricePerDay=bufferPantalla.pricePerDay;
					}
					break;
			}
		}
		utn_getChar("¿Desea seguir modificando este ID?(Y/N)", "Error. ", &answer, 'Y', 'N', 3);
		}while(answer!='N');
		retorno = 0;
	}
	return retorno;
}

/**
 * \brief pantalla_removeMenu: Remove a Employee by Id (put isEmpty Flag in TRUE)
 * \param Employee* list: Pointer to array of employees
 * \param int len: Array length
 * \param int *firstLoad: variable to check if there is even one entry loaded and
 *  safeguard to prevent errors if all data is erased
 * \return (-1) Error / (0) Ok
 */

int pantalla_removeMenu(Pantalla* list, int len,int *firstLoad)
{
	int retorno = -1;
	int idToSearch;

	if(*firstLoad == FALSE)
	{
		printf("\nERROR. NO HAY DATOS INGRESADOS.\n");
	}
	else
	{
		if(utn_getIntNumber("Ingrese el ID a eliminar:","Error, no es un ID valido. ",&idToSearch,3,INT_MAX,1)==0 &&
		   pantalla_remove(list,QTY_PANTALLAS,idToSearch)== 0)
		{
			for(int i = 0; i < len; i++)
			{
				if(list[i].isEmpty == TRUE)
				{
					*firstLoad = FALSE;
				}
				else
				{
					*firstLoad = TRUE;
					break;
				}
			}
			retorno = 0;
		}
	}
	return retorno;
}

/**
 * \brief pantalla_remove: Remove a Employee by Id (put isEmpty Flag in TRUE)
 * \param Employee* list: Pointer to array of employees
 * \param int len: Array length
 * \param int id: id value of entry to remove
 *  safeguard to prevent errors if all data is erased
 * \return (-1) Error / (0) Ok
 */

int pantalla_remove(Pantalla* list, int len,int id)
{
	int retorno = -1;
	int indexToModify;
	char answer;

	indexToModify = pantalla_findById(list, QTY_PANTALLAS, id);

	if(list != NULL && len>0 && id > 0 && indexToModify > -1)
	{
		printf("Pantalla a eliminar\n");
		printf("Nombre y Direccion: %s %s \n", list[indexToModify].name,list[indexToModify].address);
		utn_getChar("¿Desea eliminar este ID?(Y/N)", "Error. ", &answer, 'Y', 'N', 3);
		switch(answer)
		{
			case 'Y':
				list[indexToModify].isEmpty = TRUE;
				printf("REGISTRO DE EMPLEADO BORRADO CON EXITO.");
				break;
			case'N':
				printf("REGISTRO NO BORRADO");
				break;
			default:
				printf("ERROR, INGRESE 'Y' PARA BORRAR EL REGISTRO.");
		}
		retorno = 0;
	}
	else
	{
		printf("\nERROR, ID INEXISTENTE.\n");
	}
	return retorno;
}

/**
 *  \brief pantalla_getReport: Reports employees by alphabetical order and numerical order
 *  of sector. Also gives info about total money spend on salaries, average salary and
 *  how many employees have a salary above the average.
 * \param Employee* list: Pointer to array of employees
 * \param int len: Array length
 * \param int firstLoad: variable to check if there is even one entry loaded
 * \return (-1) Error / (0) Ok
 */

int pantalla_getReport(Pantalla* list, int len, int firstLoad)
{
	int retorno = -1;
	int sortOrder;

	if(firstLoad == FALSE)
	{

		printf("\nERROR. NO HAY DATOS INGRESADOS.\n");

	}
	else
	{
		if(utn_getIntNumber("\n1- Orden Descendente"
						    "\n2- Orden Ascendente"
						    "\nOpcion:","Error. ",&sortOrder,3,2,1)==0)
		{
			if(list!= NULL && len > 0)
			{
				pantalla_print(list, QTY_PANTALLAS);
				pantalla_sort(list, QTY_PANTALLAS, sortOrder);
				retorno = 0;
			}
		}
	}
	return retorno;
}

/**
 *  \brief pantalla_sort: Sort the elements in the array of employees, the argument order
 * indicate UP or DOWN order
 * \param Employee* list: Pointer to array of employees
 * \param int len: Array length
 * \param int order: [2] indicate UP (order Z->A) - [1] indicate DOWN (order A->Z)
 * \return (-1) Error / (0) Ok
 */

int pantalla_sort(Pantalla* list, int len, int order)
{
	int retorno = 0;

	if (list != NULL && len > 0 && order >0)
	{
		pantalla_sortByFileNumber(list, QTY_PANTALLAS, order);
		pantalla_sortByLastName(list, QTY_PANTALLAS, order);
		retorno = 0;
	}
	return retorno;
}

/**
 *  \brief pantalla_sortByLastName the elements in the array by last name and name
 * \param Employee* list: Pointer to array of employees
 * \param int len: Array length
 * \param int order: [2] indicate UP (order Z->A) - [1] indicate DOWN (order A->Z)
 * \return (-1) Error / (0) Ok
 */

int pantalla_sortByLastName(Pantalla* list, int len, int order)
{
	int retorno = -1;
	int sorted;
	Pantalla bufferPantalla;

	if(list != NULL && len > 0 && (order == 1 || order == 2))
	do
	{
		sorted = TRUE;
		for(int i = 0; i < (len-1); i++)
		{
			if((order == 1 &&
			  (strncmp(list[i].name, list[i + 1].name,LONG_NOMBRE)>0 ||
			  (strncmp(list[i].name, list[i + 1].name,LONG_NOMBRE)==0 &&
			   strncmp(list[i].address, list[i + 1].address,LONG_NOMBRE)>0))) ||
			   (order == 2 &&
			  (strncmp(list[i].name, list[i + 1].name,LONG_NOMBRE)<0 ||
			  (strncmp(list[i].name, list[i + 1].name,LONG_NOMBRE)==0 &&
			   strncmp(list[i].address, list[i + 1].address,LONG_NOMBRE)<0))))
			{
				bufferPantalla = list[i];
				list[i] = list[i + 1];
				list[i + 1] = bufferPantalla;
				sorted = FALSE;
			}
		}
	}while(sorted == FALSE);
	retorno = 0;
	return retorno;
}


/**
 *  \brief pantalla_sortByFileNumber the elements in the array by last name and name
 * \param Employee* list: Pointer to array of employees
 * \param int len: Array length
 * \param int order: [2] indicate UP (order Z->A) - [1] indicate DOWN (order A->Z)
 * \return (-1) Error / (0) Ok
 */

int pantalla_sortByFileNumber(Pantalla* list, int len, int order)
{
	int retorno = -1;
	int sorted;
	Pantalla bufferPantalla;

	if(list != NULL && len > 0 && (order == 1 || order == 2))
	do
	{
		sorted = TRUE;
		for(int i = 0; i < (len-1); i++)
		{
			if((order == 1 && list[i].pantallaType < list[i + 1].pantallaType) ||
			   (order == 2 && list[i].pantallaType < list[i + 1].pantallaType))
			{
				bufferPantalla = list[i];
				list[i] = list[i + 1];
				list[i + 1] = bufferPantalla;
				sorted = FALSE;
			}

		}
	}while(sorted == FALSE);
	retorno = 0;
	return retorno;
}

/**
 * \brief pantalla_print: print the content of employees array
 * \param Employee* list: Pointer to array of employees
 * \param int len: Array length
 * \return (-1) Error / (0) Ok*
 */

int pantalla_print(Pantalla* list, int len)
{
	int retorno = -1;
	if(list != NULL && len > 0)
	{
		printf("\nID |Nombre        |Direccion          |Tipo  |Precio(Por Dia)\n");
		for(int i=0;i< len ;i++)
		{
			if(list[i].isEmpty == FALSE)
			{
				printf("%d %-15s %-15s %-6d  %-6.2f\n",list[i].id,list[i].name,list[i].address,list[i].pantallaType,list[i].pricePerDay);
			}
		}
		retorno = 0;
	}
	return retorno;
}
