 /**
 ============================================================================
 Name        : publicidad.c
 Author      : Gonzalo Sinnott Segura
 Version     :
 Copyright   :
 Description : Library publicidad.c
 ============================================================================
 */

#include <stdio_ext.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include "mi_biblioteca.h"
#include "publicidad.h"
#include "pantalla.h"

static int generateNewId(void);

/**
 * \brief initPublicidad: To indicate that all positions in the array are empty,
 * this function put the flag (isEmpty) in TRUE in all position of the array
 * \param sEmployee* list: Pointer to array of employees
 * \param int len: Array length
 * \return (-1) Error / (0) Ok
 */

int initPublicidad(Publicidad* list, int len)
{
	int retorno = -1;
	if(list != NULL && len > 0)
	{
		for(int i=0;i<len;i++)
		{
			list[i].isEmpty = TRUE;
		}
		retorno = 0;
	}
	return retorno;
}

/**
 *  \brief publicidad_alta: Asks the user for the student data
 * \param Publicidad* list: Pointer to array of employees
 * \param int len: Array length
 * \param int firstLoad: Pointer to space in memory where is the
 *  variable to indicate if an entry is loaded
 * \return (-1) Error / (0) Ok
 */

int publicidad_alta(Publicidad* list,int len, int *firstLoad)
{
	int retorno = -1;
	int id;
	int cuit;
	char publicidadName;
	int publicidadDuracion;
	int index;

	if(list != NULL && len > 0 && firstLoad >0 && publicidad_checkFirstEmptyIndex(list, QTY_PUBLICIDADES, &index)==0)
	{
		if(publicidad_getForm(&cuit, publicidadName, &publicidadDuracion)== 0)
		{
			id=generateNewId();
			if(publicidad_addData(list, len, id, cuit, publicidadName, publicidadDuracion)==0)
			{
				*firstLoad = TRUE;
				retorno=0;
			}
		}
		else
		{
			printf("\nERROR EN LA CARGA DEL EMPLEADO.\n");
		}
	}
	else
	{
		printf("\nNO SE PUEDEN CARGAR MAS REGISTROS.\n");
	}
	return retorno;
}

/**
 *  \brief publicidad_checkFirstEmptyIndex: Checks first empty index in the array
 * this function search the array for the first index with the value TRUE in the isEmpty item
 * \param sEmployee* list: Pointer to array of employees
 * \param int len: Array length
 * \param int *EmptyIndex: Pointer to position of first empty index.
 * \return (-1) Error / (0) Ok
 */

int publicidad_checkFirstEmptyIndex(Publicidad* list, int len, int *emptyIndex)
{
	int retorno = -1;
	if(list != NULL && len >0 && emptyIndex != NULL)
	{
		for(int i = 0; i < len; i++)
		{
			if(list[i].isEmpty == TRUE)
			{
				*emptyIndex = i;
				retorno = 0;
				break;
			}
		}
	}
	return retorno;
}

/**
 *  \brief publicidad_getForm: Brings up a menu for the user to complete with info
 * \param char *name: Pointer to place to store name
 * \param char *lastName: Pointer to place to store last name
 * \param float *salary: Pointer to place to store salary
 * \param int *sector: Pointer to place to store sector
 * \return (-1) Error / (0) Ok
 */

int publicidad_getForm(int *cuit,char publicidadName[],int *publicidadDuracion)
{
	int retorno = -1;

	if(publicidadName != NULL && cuit > 0 && publicidadDuracion > 0)
	{
		if((utn_getAlphaNum("Ingrese Nombre de la Publicidad:", "Error. ", publicidadName, 3, LONG_NOMBRE)==0) &&
		   (utn_getIntNumber("Ingrese CUIT::", "\nError. ", cuit, 3, MAX_CUIL,MIN_CUIL)== 0) &&
		   (utn_getIntNumber("Ingrese cantidad de dias a cotratar: ", "\nError. ", publicidadDuracion, 3, 9999, 1)== 0))
		{
			retorno = 0;
		}
	}
	return retorno;
}

/**
 *  \brief generateNewId: Generates a new ID that's +1 from previous loaded employee ID.
 */

static int generateNewId(void)
{
	static int id;

	id = id+1;
	return id;
}

/**
 *  \brief publicidad_addData: add in a existing list of employees the values received
 *  as parameters in the first empty position.
 * \param Employee* list: Pointer to array of employees
 * \param int len: Array length
 * \param int id: id generated by generateNewId() function
 * \param char name[]: Input by user from getEmployeeForm
 * \param char lastName[]: Input by user from getEmployeeForm
 * \param float salary: Input by user from getEmployeeForm
 * \param int sector: Input by user from getEmployeeForm
 * \return (-1) Error / (0) Ok
 */

int publicidad_addData(Publicidad* list,int len,int id,int cuit, char publicidadName[], int publicidadDuracion)
{
	int retorno = -1;
	int emptyIndex;

	if(publicidad_checkFirstEmptyIndex(list, QTY_PUBLICIDADES, &emptyIndex)==0)
	{
		list[emptyIndex].id=id;
		strcpy(list[emptyIndex].publicidadName,publicidadName);
		list[emptyIndex].cuit = cuit;
		list[emptyIndex].publicidadDuracion = publicidadDuracion;
		list[emptyIndex].isEmpty=FALSE;
		printf("\nEl ID para la publicidad %s es: %d\n",list[emptyIndex].publicidadName,list[emptyIndex].id);
		retorno=0;
	}

    return retorno;
}

/**
 *  \brief publicidad_findById: find an Employee by Id then returns the index position in array.
 * \param Employee* list: Pointer to array of employees
 * \param int len: Array length
 * \param int id: id to search
 * \return Return employee index position or (-1) if ERROR
 */

int publicidad_findById(Publicidad* list, int len,int id)
{
	int retorno;

	if (list != NULL && len > 0 && id > 0)
	{
		for (int i = 0; i < len; i++)
		{
			if(list[i].isEmpty == FALSE && list[i].id == id )
			{
				retorno = i;
				break;
			}
		}
	}
	return retorno;;
}

/**
 * \brief publicidad_modifyMenu: Modifies the data of an Employee by given Id.
 * Allows to modify individual fields of the employee by a switch
 * \param Employee* list: Pointer to array of employees
 * \param int len: Array length
 * \param int firstLoad: variable to check if there is even one entry loaded
 * \return (-1) Error / (0) Ok
 */

int publicidad_modifyMenu(Publicidad* list, int len, int firstLoad)
{
	int retorno = -1;
	int idToSearch;

	if(firstLoad == FALSE)
	{
		printf("\nERROR. NO HAY DATOS INGRESADOS.\n");
	}
	else
	{
		if(utn_getIntNumber("Ingrese el ID a modificar:","Error, no es un ID valido. ",&idToSearch,3,INT_MAX,1)==0 &&
		   publicidad_modify(list,QTY_PUBLICIDADES,idToSearch)== 0)
		{
			retorno = 0;
		}
		else
		{
			printf("\nERROR, ID INEXISTENTE.\n");
		}
	}
	return retorno;
}

/**
 * \brief publicidad_modify: Modifies the data of an Employee by given Id.
 * Allows to modify individual fields of the employee by a switch
 * \param Employee* list: Pointer to array of employees
 * \param int len: Array length
 * \param int firstLoad: variable to check if there is even one entry loaded
 * \return (-1) Error / (0) Ok
 */

int publicidad_modify(Publicidad* list, int len,int id)
{
	int retorno = -1;
	int choosenOption;
	char answer;
	int indexToModify;

	Publicidad bufferPublicidad;

	indexToModify = publicidad_findById(list, QTY_PUBLICIDADES, id);

	if(list != NULL && len>0 && id > 0 && indexToModify > -1)
	{
		do
		{
			printf("Publicidad a modificar\n");
			printf("Cantidad de Dias contratados originalmente: %d\n",
					list[indexToModify].publicidadDuracion);
			if(utn_getIntNumber("Cantidad de dias a contratar::", "\nError. ", &bufferPublicidad.publicidadDuracion, 3, 2, 1)==0)
			{
				list[indexToModify].publicidadDuracion=bufferPublicidad.publicidadDuracion;
			}
			utn_getChar("¿Desea seguir modificando esta publicidad?(Y/N)", "Error. ", &answer, 'Y', 'N', 3);
		}while(answer!='N');
		retorno = 0;
	}
	return retorno;
}

/**
 * \brief publicidad_removeMenu: Remove a Employee by Id (put isEmpty Flag in TRUE)
 * \param Employee* list: Pointer to array of employees
 * \param int len: Array length
 * \param int *firstLoad: variable to check if there is even one entry loaded and
 *  safeguard to prevent errors if all data is erased
 * \return (-1) Error / (0) Ok
 */

int publicidad_removeMenu(Publicidad* list, int len,int *firstLoad)
{
	int retorno = -1;
	int idToSearch;

	if(*firstLoad == FALSE)
	{
		printf("\nERROR. NO HAY DATOS INGRESADOS.\n");
	}
	else
	{
		if(utn_getIntNumber("Ingrese el ID a eliminar:","Error, no es un ID valido. ",&idToSearch,3,INT_MAX,1)==0 &&
		   publicidad_remove(list,QTY_PUBLICIDADES,idToSearch)== 0)
		{
			for(int i = 0; i < len; i++)
			{
				if(list[i].isEmpty == TRUE)
				{
					*firstLoad = FALSE;
				}
				else
				{
					*firstLoad = TRUE;
					break;
				}
			}
			retorno = 0;
		}
	}
	return retorno;
}

/**
 * \brief publicidad_remove: Remove a Employee by Id (put isEmpty Flag in TRUE)
 * \param Employee* list: Pointer to array of employees
 * \param int len: Array length
 * \param int id: id value of entry to remove
 *  safeguard to prevent errors if all data is erased
 * \return (-1) Error / (0) Ok
 */

int publicidad_remove(Publicidad* list, int len,int id)
{
	int retorno = -1;
	int indexToModify;
	char answer;

	indexToModify = publicidad_findById(list, QTY_PUBLICIDADES, id);

	if(list != NULL && len>0 && id > 0 && indexToModify > -1)
	{
		printf("Publicidad a eliminar\n");
		printf("Nombre y CUIL: %s %d \n", list[indexToModify].publicidadName,list[indexToModify].cuit);
		utn_getChar("¿Desea eliminar este ID?(Y/N)", "Error. ", &answer, 'Y', 'N', 3);
		switch(answer)
		{
			case 'Y':
				list[indexToModify].isEmpty = TRUE;
				printf("REGISTRO DE EMPLEADO BORRADO CON EXITO.");
				break;
			case'N':
				printf("REGISTRO NO BORRADO");
				break;
			default:
				printf("ERROR, INGRESE 'Y' PARA BORRAR EL REGISTRO.");
		}
		retorno = 0;
	}
	else
	{
		printf("\nERROR, ID INEXISTENTE.\n");
	}
	return retorno;
}

/**
 *  \brief publicidad_getReport: Reports employees by alphabetical order and numerical order
 *  of sector. Also gives info about total money spend on salaries, average salary and
 *  how many employees have a salary above the average.
 * \param Employee* list: Pointer to array of employees
 * \param int len: Array length
 * \param int firstLoad: variable to check if there is even one entry loaded
 * \return (-1) Error / (0) Ok
 */

int publicidad_getReport(Publicidad* list, int len, int firstLoad)
{
	int retorno = -1;
	int sortOrder;

	if(firstLoad == FALSE)
	{

		printf("\nERROR. NO HAY DATOS INGRESADOS.\n");

	}
	else
	{
		if(utn_getIntNumber("\n1- Orden Descendente"
						    "\n2- Orden Ascendente"
						    "\nOpcion:","Error. ",&sortOrder,3,2,1)==0)
		{
			if(list!= NULL && len > 0)
			{
				publicidad_print(list, QTY_PUBLICIDADES);
				publicidad_sort(list, QTY_PUBLICIDADES, sortOrder);
				retorno = 0;
			}
		}
	}
	return retorno;
}

/**
 *  \brief publicidad_sort: Sort the elements in the array of employees, the argument order
 * indicate UP or DOWN order
 * \param Employee* list: Pointer to array of employees
 * \param int len: Array length
 * \param int order: [2] indicate UP (order Z->A) - [1] indicate DOWN (order A->Z)
 * \return (-1) Error / (0) Ok
 */

int publicidad_sort(Publicidad* list, int len, int order)
{
	int retorno = 0;

	if (list != NULL && len > 0 && order >0)
	{
		publicidad_sortByFileNumber(list, QTY_PUBLICIDADES, order);
		publicidad_sortByLastName(list, QTY_PUBLICIDADES, order);
		retorno = 0;
	}
	return retorno;
}

/**
 *  \brief publicidad_sortByLastName the elements in the array by last name and name
 * \param Employee* list: Pointer to array of employees
 * \param int len: Array length
 * \param int order: [2] indicate UP (order Z->A) - [1] indicate DOWN (order A->Z)
 * \return (-1) Error / (0) Ok
 */

int publicidad_sortByLastName(Publicidad* list, int len, int order)
{
	int retorno = -1;
	int sorted;
	Publicidad bufferPublicidad;

	if(list != NULL && len > 0 && (order == 1 || order == 2))
	do
	{
		sorted = TRUE;
		for(int i = 0; i < (len-1); i++)
		{
			if((order == 1 &&
			  strncmp(list[i].publicidadName, list[i + 1].publicidadName,LONG_NOMBRE)>0) ||
			   (order == 2 &&
			   strncmp(list[i].publicidadName, list[i + 1].publicidadName,LONG_NOMBRE)<0))
			{
				bufferPublicidad = list[i];
				list[i] = list[i + 1];
				list[i + 1] = bufferPublicidad;
				sorted = FALSE;
			}
		}
	}while(sorted == FALSE);
	retorno = 0;
	return retorno;
}


/**
 *  \brief publicidad_sortByFileNumber the elements in the array by last name and name
 * \param Employee* list: Pointer to array of employees
 * \param int len: Array length
 * \param int order: [2] indicate UP (order Z->A) - [1] indicate DOWN (order A->Z)
 * \return (-1) Error / (0) Ok
 */

int publicidad_sortByFileNumber(Publicidad* list, int len, int order)
{
	int retorno = -1;
	int sorted;
	Publicidad bufferPublicidad;

	if(list != NULL && len > 0 && (order == 1 || order == 2))
	do
	{
		sorted = TRUE;
		for(int i = 0; i < (len-1); i++)
		{
			if((order == 1 && list[i].publicidadDuracion < list[i + 1].publicidadDuracion) ||
			   (order == 2 && list[i].publicidadDuracion < list[i + 1].publicidadDuracion))
			{
				bufferPublicidad = list[i];
				list[i] = list[i + 1];
				list[i + 1] = bufferPublicidad;
				sorted = FALSE;
			}

		}
	}while(sorted == FALSE);
	retorno = 0;
	return retorno;
}

/**
 * \brief publicidad_print: print the content of employees array
 * \param Employee* list: Pointer to array of employees
 * \param int len: Array length
 * \return (-1) Error / (0) Ok*
 */

int publicidad_print(Publicidad* list, int len)
{
	int retorno = -1;
	if(list != NULL && len > 0)
	{
		printf("\nID |CUIT        |PUBLICIDAD          |DIAS CONTRATADOS\n");
		for(int i=0;i< len ;i++)
		{
			if(list[i].isEmpty == FALSE)
			{
				printf("%d %-15s %d\n",list[i].cuit,list[i].publicidadName,list[i].publicidadDuracion);
			}
		}
		retorno = 0;
	}
	return retorno;
}
